[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcode = "0.6.9"
fastrand = "2.4.1"
tempfile = "3.27.0"

[features]
default = []
use-legacy-search = []

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "engine_bench" # This must match the filename in benches/ exactly
harness = false  